---
kind: pipeline
name: "Deploy"

platform:
  arch: arm64

trigger:
  event:
    - push
    - promote

environment:
  REGISTRY_GROUP: smashedr

steps:
  - name: "Variables"
    image: ubuntu
    commands:
      - export ENV_NAME=$(if [ "${DRONE_DEPLOY_TO}" == "prod" ];then echo 'prod';else echo 'dev';fi)
      - echo DRONE_DEPLOY_TO $${DRONE_DEPLOY_TO}
      - echo ENV_NAME $${ENV_NAME}

  - name: "Service Configs"
    image: alpine/git
    commands:
      - echo DRONE_DEPLOY_TO $${DRONE_DEPLOY_TO}
      - echo ENV_NAME $${ENV_NAME}
#      - cd service-configs
#      - git init
#      - git remote add origin https://github.com/smashedr/django4drone.git
#      - git config core.sparseCheckout true
#      - echo "README.md" >> .git/info/sparse-checkout
#      - git pull origin master

  - name: "Dev Deploy"
    image: ubuntu
    when:
      branch:
        exclude:
          - master
    commands:
      - echo DRONE_DEPLOY_TO $${DRONE_DEPLOY_TO}
      - echo ENV_NAME $${ENV_NAME}
      - echo ----------
      - echo DRONE_REPO $${DRONE_REPO}
      - echo DRONE_REPO_NAME $${DRONE_REPO_NAME}
      - echo DRONE_REPO_OWNER $${DRONE_REPO_OWNER}
      - echo DRONE_BRANCH $${DRONE_BRANCH}
      - echo DRONE_COMMIT_MESSAGE $${DRONE_COMMIT_MESSAGE}
      - echo DRONE_REPO_LINK $${DRONE_REPO_LINK}

  - name: "Prod Deploy"
    image: ubuntu
    when:
      event:
        - promote
    commands:
      - echo DRONE_DEPLOY_TO $${DRONE_DEPLOY_TO}
      - echo ----------
      - echo DRONE_REPO $${DRONE_REPO}
      - echo DRONE_REPO_NAME $${DRONE_REPO_NAME}
      - echo DRONE_REPO_OWNER $${DRONE_REPO_OWNER}
      - echo DRONE_BRANCH $${DRONE_BRANCH}
      - echo DRONE_COMMIT_MESSAGE $${DRONE_COMMIT_MESSAGE}
      - echo DRONE_REPO_LINK $${DRONE_REPO_LINK}
