---
kind: pipeline
name: "Deploy"

platform:
  arch: arm64

trigger:
  event:
    - push
    - promote

environment:
  REGISTRY_GROUP: smashedr

steps:
  - name: "Deploy"
    image: ubuntu:latest
    when:
      branch:
        exclude:
          - master
    commands:
      - echo DRONE_DEPLOY_TO $${DRONE_DEPLOY_TO}
      - echo ----------
      - echo DRONE_REPO $${DRONE_REPO}
      - echo DRONE_REPO_NAME $${DRONE_REPO_NAME}
      - echo DRONE_REPO_OWNER $${DRONE_REPO_OWNER}
      - echo DRONE_BRANCH $${DRONE_BRANCH}
      - echo DRONE_COMMIT_MESSAGE $${DRONE_COMMIT_MESSAGE}
      - echo DRONE_REPO_LINK $${DRONE_REPO_LINK}

#  - name: "Prod Deploy"
#    image: ubuntu:latest
#    when:
#      event:
#        - promote
#    commands:
#      - echo DRONE_DEPLOY_TO $${DRONE_DEPLOY_TO}
#      - echo ----------
#      - echo DRONE_REPO $${DRONE_REPO}
#      - echo DRONE_REPO_NAME $${DRONE_REPO_NAME}
#      - echo DRONE_REPO_OWNER $${DRONE_REPO_OWNER}
#      - echo DRONE_BRANCH $${DRONE_BRANCH}
#      - echo DRONE_COMMIT_MESSAGE $${DRONE_COMMIT_MESSAGE}
#      - echo DRONE_REPO_LINK $${DRONE_REPO_LINK}
