---
kind: pipeline
name: "Deploy"

platform:
  arch: arm64

trigger:
  event:
    - push
  branch:
    exclude:
      - master

environment:
  REGISTRY_GROUP: smashedr

steps:
  - name: "Dev Deploy"
    image: ubuntu:latest
    commands:
      - echo REGISTRY_GROUP0 $REGISTRY_GROUP
      - echo REGISTRY_GROUP1 ${REGISTRY_GROUP}
      - echo REGISTRY_GROUP2 $${REGISTRY_GROUP}

  - name: "Prod Deploy"
    image: ubuntu:latest
    when:
      event:
        - promote
    commands:
      - echo REGISTRY_GROUP0 $REGISTRY_GROUP
      - echo REGISTRY_GROUP1 ${REGISTRY_GROUP}
      - echo REGISTRY_GROUP2 $${REGISTRY_GROUP}
